### ISSUE TITLE
Strange laser behaviour in some edgecases

### ISSUE THREAD

**Issue by KdVos** [tue-robotics/emc_simulator#39] opened 2023-02-09 15:19 UTC
Currently not urgent, but in some edge cases (see below) the laser behavior is showing strange results

![image](https://user-images.githubusercontent.com/50488480/217853484-68f15dad-b40f-4e1f-b704-db917f4661e6.png)

**Comment by KdVos** [comment] 2023-03-03 12:19
Don't have time now to check, and I'm pretty sure it isn't the case, but did this also occur in previous version of the visualizer, i.e. before we used RViz?

**Comment by PetervDooren** [comment] 2023-03-03 16:03
Tried to generate the map shape with the method from https://github.com/tue-robotics/geolib2/blob/master/include/geolib/HeightMap.h But the behaviour persists. Suggesting this is a fault in geolib. made issue https://github.com/tue-robotics/geolib2/issues/73 as the first step in finding this thing

**Comment by PetervDooren** [comment] 2023-03-07 14:24
After testing with the geolib tool test_geolib_lrf 
`rosrun geolib2 test_geolib_lrf`
This error could not be reproduced. This would suggest it is not caused by the lrf model.

**Comment by MatthijsBurgh** [comment] 2023-03-07 14:35
@PetervDooren have you tested with multiple boxes?

**Comment by MatthijsBurgh** [comment] 2023-03-07 14:37
@KdVos you had an issue with correct and incorrect heightmaps. Could you generate the causing the issue and delete the wall that is renderer,but shouldn't. Is the correct wall than renderer for its full length?

**Comment by PetervDooren** [comment] 2023-03-07 14:46
> @PetervDooren have you tested with multiple boxes?

I have not

**Comment by MatthijsBurgh** [comment] 2023-03-07 14:53
I think the problem is in that part of the code. So I suggest to modify the test a bit to add two boxes.

**Comment by MatthijsBurgh** [comment] 2023-03-07 15:07
Ok, can we reproduce this exact setup in test_geolib_lrf? So we either can debug the issue there or try to find the difference between the two, to find the issue.

**Comment by PetervDooren** [comment] 2023-03-07 15:28
One example of a broken situation can be seen with
`rosrun geolib2 test_geolib_lrf 50 -0.5 0.395 0.4 3 0.1`

**Comment by PetervDooren** [comment] 2023-03-07 15:30
![hahawebrokeit](https://user-images.githubusercontent.com/19806646/223468783-b13c179d-446a-4602-b4fe-2dcf207bf556.png)

**Comment by KdVos** [comment] 2023-03-08 08:44
Running the above, after adapting the test to include a laser from -95 to 95 degrees gives the following result.

![image](https://user-images.githubusercontent.com/50488480/223665254-0b02e245-3077-4365-9c07-5ab4a4fd4077.png)

**Comment by MatthijsBurgh** [comment] 2023-03-08 09:01
Aka the `half_circle` logic is incorrect. This assume the laser always has a range bigger than 180 degrees. (Significant enough bigger than 180 degrees, so int rounding, doesn't brings you back to a 180 degrees sensor on internal calculated variables.)

Though this doesn't explain the issues with emc_simulator which has a range of around 240 degrees. But the I think that is an another edge case in the same buggy logic.

**Comment by PetervDooren** [comment] 2023-03-08 10:21
@ThijsBeurskensTUE hypothesis was that it was related to the `half_circle` logic because the check is done with the capped indices.

**Comment by MatthijsBurgh** [comment] 2023-03-09 21:50
Fixed by https://github.com/tue-robotics/geolib2/pull/74, https://github.com/tue-robotics/geolib2/pull/75

**Closed by MatthijsBurgh** 2023-03-09 21:50 UTC
Labels: bug
